title: "Anmol Dura â€” Journey, Cloud & Life"
description: "My honest journey: cloud computing, projects, work, gym, and life in Toronto."
url: "https://anmol-dura.github.io" # the base hostname & protocol for your site
baseurl: "/anmol-dura-cloud-journey-blog"

author:
name: "Anmol Dura"
email: "anmoldura8@gmail.com"

theme: minima

timezone: America/Toronto

# Nav: which markdown pages show in the top menu
header_pages:
  - about.md
  - projects.md
  - daily.md
  - blog.md
  - tags.md

# Plugins supported by GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections for daily logs
collections:
  daily:
    output: true
    permalink: /daily/:title/

# Markdown & permalinks
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/
